关于 static 的几个容易混淆的概念
rust-zh/faq pull request #9
Opened 2021-12-02 03:42 UTC by driftluo

望指正

2021-12-02 09:19 UTC, mzji commented on content/static-variable-and-static-lifetime.md 
> +通常，&'static 的变量可以通过 leak、static 变量、显示声明 'static str 等方式生成。
```suggestion
通常，`&'static` 的变量可以通过 leak、static 变量、显式声明 `&'static str` 等方式生成。
```

2021-12-02 10:11 UTC, mzji commented on content/static-variable-and-static-lifetime.md 
> +如果一个 `T: 'static` ，那么就是这个类型在任意情况下都有效，换句话说就是里面不包含局部引用。
```suggestion
如果 `T: 'static` ，那么可以说 T 在任意情况下都有效，也即 T 中不包含生命期短于 'static 的引用。
```

2021-12-02 10:12 UTC, mzji commented on content/static-variable-and-static-lifetime.md 
> +接收方可以保存这个 T 直到它想 drop 为止，在此期间内，这个 T 必须是有效的。
```suggestion
接收方可以保存 T 的值直到需要 drop 它为止，在此期间内，T 的值必须一直是有效的。
```

2021-12-02 12:31 UTC, upsuper reviewed
内容还没细读，一些体例问题

2021-12-02 12:31 UTC, upsuper commented on content/static-variable-and-static-lifetime.md 
> +## static 变量、T: 'static、&'static T 的区别
第一级标题应该用 `#`。

2021-12-02 12:31 UTC, upsuper commented on content/static-variable-and-static-lifetime.md 
> +#### static 变量
二级标题应该用 `##`。

2021-12-02 12:31 UTC, upsuper commented on content/static-variable-and-static-lifetime.md 
> +static 变量在整个程序生命期内不会调用 drop。
请把一段的所有行并在一起，因为我无意实现软断行的支持（

2021-12-02 12:31 UTC, upsuper commented on content/static-variable-and-static-lifetime.md 
> +[static 变量][ref]，形如 `static A: String = "static".to_string()`, 经常与 const 变量相比较，它俩的
这个例子编译不过，最好应该用一个能过的例子？

2021-12-02 12:31 UTC, upsuper commented on content/static-variable-and-static-lifetime.md 
> +#### T: 'static
代码应该用反引号括起来 
```suggestion
#### `T: 'static`
```

2021-12-02 12:31 UTC, upsuper commented on content/static-variable-and-static-lifetime.md 
> +如果 `T: 'static` ，那么可以说 T 在任意情况下都有效，也即 T 中不包含生命期短于 'static 的引用。
这里的 `T` 和 `'static` 应该也都是代码，应该用反引号括起来。

2021-12-02 12:31 UTC, upsuper commented on content/static-variable-and-static-lifetime.md 
> +但它没说明任何 ownership 信息，你可能 own 它（你负责 drop ，比如 String ），也可能不 own 它
ownership => 所有权
own => 拥有

`drop` 和 `String` 也应该看作代码，然后 `String` 和标点符号间不需要空格。

2021-12-02 12:31 UTC, upsuper commented on content/static-variable-and-static-lifetime.md 
> +作为参数的 泛型约束声明 使用了 `T: 'static` 时，这意味着，用户需要传入一个不包含局部引用的类型给接收方，
如果你想给“泛型约束声明”加上英文注解的话，或者是在 `glossary.toml` 里添加，然后这里用 `[泛型约束声明]`，或者是直接在这里写 `[泛型约束声明](<> "...")` 取决于这个名称是否会常用。

2021-12-02 12:31 UTC, upsuper commented on content/static-variable-and-static-lifetime.md 
> +当一个类型被声明为 `&'static` 生命期时，它可以被 `coerced` 成更短的生命期，也就是说 `'static: 'a`。
这里的coerced显然不是代码，不应该用反引号括起来，最好是能翻译成中文……可以参考[Rust 语言术语中英文对照表](https://github.com/rust-lang-cn/english-chinese-glossary-of-rust/blob/master/rust-glossary.md)里的翻译方式。

2021-12-02 12:31 UTC, upsuper commented on content/static-variable-and-static-lifetime.md 
> +通常，`&'static` 的变量可以通过 leak、static 变量、显示声明 `'static str` 等方式生成。
“显**式**”

2021-12-02 12:34 UTC, upsuper commented on content/static-variable-and-static-lifetime.md 
> +[HRTBs]: https://doc.rust-lang.org/nomicon/hrtb.html
这两个链接并没有在文中引用，可以去掉

2021-12-02 12:34 UTC, upsuper commented on content/static-variable-and-static-lifetime.md 
> +[ref]: https://doc.rust-lang.org/nightly/std/keyword.static.html
一般我是链接到stable版的文档的

2021-12-04 11:31 UTC, upsuper commented
在你编写的内容的基础上，我考虑或许这么写会更好一些：

----

# `&'static T`、`T: 'static` 和 `static` 关键字分别表示什么？它们之间有什么联系？

`&'static T` 表示的是一个指向类型为 `T` 的对象的引用，它的[生命周期](<> "lifetime")为 `'static`。这里的生命周期 `'static` 表示这个引用所指向的对象在程序的整个运行期间都不会被释放。这样的引用最常来自于字面量和对字面量的引用（如 `"hello world"` 的类型为 `&'static str`、`&[1i32, 2, 3]` 的类型为 `&'static [i32; 3]`），但它也可以来自于对常量或静态变量的引用，以及通过如 [`Vec::leak`][vec-leak] 等方法放弃[所有权](<> "ownership")来获得。由于 `'static` 生命周期长于任何其他生命周期，一个 `&'static T` 类型的引用可以安全地被[强制转换](<> "coerce")为一个标注为任何生命周期的引用 `&'a T`。

`T: 'static` 表示的是一个[类型约束](<> "type bound")，它表明类型 `T` 在程序的整个运行期间都是有效的，也即 `T` 中不包含引用，或包含的所有引用的生命周期都为 `'static`，举例来说
* 类型 `struct Alpha(String, Vec<usize>);` 符合符合这一约束，因为类型中不包含引用；
* 类型 `struct Beta(&'static str);` 也符合这一约束，因为类型中的所有引用都是 `'static` 的；
* 类型 `struct Gamma<'a>(&'a [usize]);` 仅当在 `'a` 为 `'static` 时符合这一约束，否则不符合；
* 类型 `struct Delta<T>(T);` 仅当 `T` 符合这一约束时，它也符合这一约束，否则不符合。

如果一个值的类型不满足这一约束，这个值必须在类型上所标注的生命周期结束之前被释放掉。如果满足，则这个值可以存在任意长时间。显然一个值的生命周期不能超越约束其类型的生命周期，因此任何 `&'static T` 引用中的 `T` 必然要满足 `T: 'static`。

以 [`static` 关键字][static-keyword] 声明的，形如 `static FOO: [i32; 5] = [1, 2, 3, 4, 5];` 的变量是[静态变量](<> "static variable)。一个静态变量在程序的整个运行期间是唯一的，有唯一的地址，而且不会被释放。它可以被看作是Rust里的全局变量。显然，如果一个静态变量的类型为 `T`，这个类型必须满足 `T: 'static`，并且引用这个静态变量可以得到一个 `&'static T`。


[vec-leak]: https://doc.rust-lang.org/std/vec/struct.Vec.html#method.leak
[static-keyword]: https://doc.rust-lang.org/std/keyword.static.html

----

几点考量：
1. FAQ当然首先得有一个问题ww
2. `&'static T` 比 `T: 'static` 和静态变量更常见，所以首先介绍
3. 虽然我个人也不喜欢“生命周期”这个翻译，但在[术语对照表](https://github.com/rust-lang-cn/english-chinese-glossary-of-rust/blob/master/rust-glossary.md)里我们已经接受了这个翻译，所以统一改用该翻译

2021-12-04 13:59 UTC, driftluo commented
> &'static T 表示的是一个指向类型为 T 的对象的引用，它的生命周期为 'static。这里的生命周期 'static 表示这个引用所指向的对象在程序的整个运行期间都不会被释放

&‘static T 不代表 T 在程序运行期间内都不会被释放，这个是常见的错误理解，只有 static 变量才能保证这一点

2021-12-04 20:44 UTC, upsuper commented
> &‘static T 不代表 T 在程序运行期间内都不会被释放，这个是常见的错误理解，只有 static 变量才能保证这一点

会在程序运行期间被释放的东西如何能有static引用？除非这程序是unsound的

2021-12-05 03:19 UTC, driftluo commented
> 会在程序运行期间被释放的东西如何能有static引用？除非这程序是unsound的

不能简单的说它是 unsound 的，这里讨论的是 &’static 会不会（有没有可能被 drop）被 drop，有两种可能：
1. 它是 unsound 的
2. 可以构建一个 带 &’static 的结构体，让它在程序结束前 drop，例如
```
use std::slice;
use std::fmt::{Debug, self};
use std::mem::ManuallyDrop;

struct A<'a> {
    inner: ManuallyDrop<Vec<usize>>,
    display: &'a mut [usize]
}

impl<'a> A<'a> {
    fn new(a: Vec<usize>) -> Self {
        let mut handle = ManuallyDrop::new(a);
        A{
            display:unsafe { slice::from_raw_parts_mut(handle.as_mut_ptr(), handle.len()) },
            inner: handle,
        }
    }
}

impl<'a> Debug for A<'a> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.display.fmt(f)
    }
}

impl<'a> Drop for A<'a> {
    fn drop(&mut self) {
        println!("drop");
       unsafe {
          ManuallyDrop::drop(&mut self.inner); 
       }
    }
}

fn display<T: Debug>(s: T) {
  println!("{:?}", s);
}

fn main() {
   let s: A<'static> = {
       let x = vec![1, 2, 3];
       A::new(x)
   };
   
   display(s);
   println!("end")
}
```

2021-12-05 03:34 UTC, upsuper commented
> 可以构建一个 带 &’static 的结构体，让它在程序结束前 drop，例如

你这里的使用方式虽然在这个程序里不会触发UB，但很难说是sound的，如果有其他东西拿到了这个static引用，它就有可能通过其他的Drop或者其他线程超出所引值的生命期边界触发UB。

2021-12-05 03:42 UTC, driftluo commented
> 你这里的使用方式虽然在这个程序里不会触发UB，但很难说是sound的，如果有其他东西拿到了这个static引用，它就有可能通过其他的Drop或者其他线程超出所引值的生命期边界触发UB。

通过假如一个 占位 field `Rc<()>`， 可以拒绝掉线程导致的问题，不允许直接拿到 display 字段可以保证 handle 与 ‘static 是一定在一起的，这些都是可以通过一些限定改成无法触发 UB 的。我的主要目的是说明，&‘static 并不是不能在程序结束前 drop 的

2021-12-05 03:42 UTC, upsuper commented
这个问题Rust By Example[说的](https://doc.rust-lang.org/rust-by-example/scope/lifetime/static_lifetime.html)是：
> As a reference lifetime `'static` indicates that the data pointed to by the reference lives for the entire lifetime of the running program. It can still be coerced to a shorter lifetime.

TRPL[说的](https://doc.rust-lang.org/book/ch10-03-lifetime-syntax.html)是：
> One special lifetime we need to discuss is `'static`, which means that this reference _can_ live for the entire duration of the program.

我想这很明确地表明语义上 `'static` 表达的就是所引值在程序整个运行期间不会被释放。

2021-12-05 03:48 UTC, driftluo commented
> 我想这很明确地表明语义上 'static 表达的就是所引值在程序整个运行期间不会被释放。

我认为这里存在歧义，或者说，存在能够构建的例外，或者说，缺少前置条件，比如在 不引用 unsafe 的场景里可以这么认为

2021-12-05 03:51 UTC, upsuper commented
> 我认为这里存在歧义，或者说，存在能够构建的例外，或者说，缺少前置条件，比如在 不引用 unsafe 的场景里可以这么认为

我认为这里表明的是它的语义，不符合语义的做法应该被认为是一种误用，使用unsafe只是误用语义的一个先决条件。我不觉得解释含义需要考虑误用的情况。而你这里的场景我认为相比于误用 `'static` 引用，直接使用指针是更加合适的做法。

2021-12-05 07:09 UTC, driftluo commented
@upsuper 我将你的建议文本稍加了一点点修改：
 
标注了 裸指针及其他特殊场景无法保证 &’static T 不被释放

> T: 'static 表示的是一个类型约束，它表明类型 T 在程序的整个运行期间都是有效的

改为 

> `T: 'static` 表示的是一个类型约束，它表明类型 T 可以在程序的整个运行期间有效

2021-12-05 10:31 UTC, uonr commented on content/static-variable-and-static-lifetime.md 
> +`T: 'static` 表示的是一个类型约束，它表明类型 T 可以在程序的整个运行期间有效，也即 T 中不包含引用，或包含的所有
或许详细解释一下 `T: 'a` 的意义比较好

> 对类型参数 `T` 用 lifetime 进行约束的 `T: 'a` 表明的是能作为 `T` 的类型中任意引用的 lifetime 都不会短过 `'a`。而如果是 `T: 'static` 的话则意味着能作为 `T` 的类型中任意引用（如果有的话）不能短过 `'static`，因为 `'static` 代表的是整个程序运行期间，所以是指类型 T 可以在程序的整个运行期间有效，也即 T 中不包含引用，或包含的所有引用的生命周期都为 'static，举例来说:

2021-12-06 09:17 UTC, pan93412 requested changes
大致上 OK。

2021-12-06 09:17 UTC, pan93412 commented on content/static-variable-and-static-lifetime.md
> +- 类型 `struct Delta<T>(T);` 仅当 `T` 符合这一约束时，它也符合这一约束，否则不符合。
這裡重複了幾次「符合這一約束」，不太好一次讀懂。或許可以用更白話的方式解釋？

2021-12-06 09:17 UTC, pan93412 commented on content/static-variable-and-static-lifetime.md
> +一个静态变量在程序的整个运行期间是唯一的，有唯一的地址，而且不会被释放。它可以被看作是Rust里的全局变量。显然，如果
中英補空的風格建議統一。

2021-12-06 09:17 UTC, pan93412 commented on content/static-variable-and-static-lifetime.md
> +一个静态变量的类型为 `T`，这个类型必须满足 `T: 'static`，并且引用这个静态变量可以得到一个 `&'static T`。
這個結尾似乎有一點讓人摸不著頭緒？我猜原本想表達的是「……這個類型必須滿足 `T: 'static`，如此一來，這個值的 reference 才是 `&'static T`。」

2021-12-06 09:27 UTC, pan93412 commented
其實中英補空說的是 "Rust" 的部分。

2021-12-06 12:00 UTC, pan93412 requested changes

2021-12-06 12:00 UTC, pan93412 commented on content/static-variable-and-static-lifetime.md
> +`&'static T` 表示的是一个指向类型为 T 的值的引用，它的[生命周期][lifetime]为 `'static`。这里的生命周期 `'static` 在语义上表示这个引用所指向的值在程序的整个运行期间都不会被释放（裸指针及其他特殊场景无法保证）。这样的引用最常来自于[字面量][literal]和对字面量的引用（如字符串字面量 `"hello world"` 的类型为 `&'stati
```
（如字符串字面量 `"hello world"` 的类型为 `&'static str`；`&[1i32, 2, 3]` 的类型为 `&'static [i32; 3]`）
```

這裡用分號比較好。

2021-12-06 12:00 UTC, pan93412 commented on content/static-variable-and-static-lifetime.md
> +- 类型 `struct Alpha(String, Vec<usize>);` 符合符合这一约束，因为类型中不包含引用；
`符合` 重複。

2021-12-06 12:08 UTC, upsuper commented on content/static-variable-and-static-lifetime.md
> +`&'static T` 表示的是一个指向类型为 T 的值的引用，它的[生命周期][lifetime]为 `'static`。这里的生命周期 `'static` 在语义上表示这个引用所指向的值在程序的整个运行期间都不会被释放（裸指针及其他特殊场景无法保证）。这样的引用最常来自于[字面量][literal]和对字面量的引用（如字符串字面量 `"hello world"` 的类型为 `&'stati
不好，为什么要用分号？

2021-12-06 12:10 UTC, pan93412 commented on content/static-variable-and-static-lifetime.md
> +`&'static T` 表示的是一个指向类型为 T 的值的引用，它的[生命周期][lifetime]为 `'static`。这里的生命周期 `'static` 在语义上表示这个引用所指向的值在程序的整个运行期间都不会被释放（裸指针及其他特殊场景无法保证）。这样的引用最常来自于[字面量][literal]和对字面量的引用（如字符串字面量 `"hello world"` 的类型为 `&'stati
兩句屬並列關係。`、` 常用於物品的並列；`；` 常用於句子的並列。不過有點矯枉過正，主要還是看你們的看法。

2021-12-06 12:15 UTC, upsuper commented
不用继续修改了……

我最后改一些地方然后合并

2021-12-06 12:47 UTC, upsuper commented on content/static-variable-and-static-lifetime.md 
> +`T: 'static` 表示的是一个类型约束，它表明类型 T 可以在程序的整个运行期间有效，也即 T 中不包含引用，或包含的所有
确实有点冗长，特别前面引用的部分也没有介绍 `&'a`，所以感觉不是特别必要……

2021-12-06 12:54 UTC, merged